# Generated by Django 3.1 on 2021-09-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_remove_todo_created_by_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='text',
            field=models.TextField(default='text'),
            preserve_default=False,
        ),
    ]
